Cha_Flow/urls.py
from django.conf.urls import url,include
from django.contrib import admin
import xadmin
from Cha_Flow import views
from users import views as user_view
from workflows import views as workflow_view

urlpatterns = [
    url(r'^brain/', xadmin.site.urls),
    url(r"^questions/",include("question_record.urls",namespace="question")),
    url(r'^workflow/',include("workflows.urls",namespace="workflow")),
    url(r'^user/',include('users.urls',namespace='users')),
    url(r"^$",views.index,name="dashboard"),
    url(r"^login",user_view.acc_login,name="login"),
    url(r"^logout",user_view.acc_logout,name="logout"),


    url(r'^403.html',views.permission_denied,name='code 403'),
    url(r'^500.html',views.page_error,name='code 500')
]

# 定义错误跳转页面
handler404 = views.page_not_found
handler403 = views.permission_denied
handler500 = views.page_error

apps/question_record/urls.py
__author__ = 'yuchen'
__date__ = '2018/11/23 13:32'

from django.conf.urls import url,include
from question_record import views


urlpatterns = [
    url(r"^index/$",views.show_index,name="show_my_questions"),
    url(r"^create/$",views.create_question,name="create_question"),
    url(r'^edit-(\d+)/$', views.edit_question,name="edit_question"),

    url(r"^kill-list$",views.question_kill_list,name="kill_question"),
    url(r"^kill-(\d+)$",views.question_kill)
]

extra_apps/DjangoUeditor/urls.py
# coding:utf-8
from django import VERSION
from .widgets import UEditorWidget, AdminUEditorWidget
from .views import get_ueditor_controller
from django.conf.urls import url

urlpatterns = [
    url(r'^controller/$', get_ueditor_controller),
]

apps/question_record/models.py
from django.db import models
from users.models import UserProfile

# Create your models here.

class QuestionRecord(models.Model):
    create_date = models.DateField("发生日期",blank=True,auto_now_add=True)
    create_time = models.TimeField("发生时间",blank=True,auto_now_add=True)
    action_time = models.TimeField("响应时间",blank=True,auto_now=True)
    position_time=models.TimeField("定位时间",blank=True,auto_now=True)
    question_result=models.CharField('问题进展', blank=True, null=True, default=None,max_length=125)
    question_memo = models.TextField('问题简述', blank=True, null=True, default=None)
    question_reason=models.CharField('问题原因',blank=True,null=True,default=None,max_length=100)
    question_range=models.CharField('问题影响范围',blank=True,null=True,default=None,max_length=50)
    class Meta:
        verbose_name = '问题记录'
        verbose_name_plural = verbose_name

class Ask_Question(models.Model):
    title = models.CharField(max_length=32)
    detail = models.TextField()
    user = models.ForeignKey(UserProfile,related_name='u')
    # ctime = models.CharField(max_length=32) # 1491527007.452494
    ctime = models.DateTimeField("提交时间",auto_now_add=True)
    status_choices = (
        (1,'未处理'),
        (2,'处理中'),
        (3,'已处理'),
    )
    status = models.IntegerField(choices=status_choices,default=1)

    processer = models.ForeignKey(UserProfile,related_name='p',null=True,blank=True)
    solution = models.TextField(null=True)
    ptime = models.DateTimeField(null=True)
    pj_choices = (
        (1, '不满意'),
        (2, '一般'),
        (3, '工作很赞'),
    )
    pingjia = models.IntegerField(choices=pj_choices,null=True,default=2)

apps/question_record/forms.py
__author__ = 'yuchen'
__date__ = '2018/11/29 00:14'

from django import forms
from django.forms import widgets

class QuestionMaker(forms.Form):
    title = forms.CharField(max_length=128,widget=widgets.TextInput(attrs={'class': 'form-control '}))
    detail = forms.CharField(widget=widgets.Textarea(attrs={'id':'detail','class':'kind-content'}))

class QuestionKill(forms.Form):
    title = forms.CharField(max_length=128,required=False,widget=widgets.TextInput(attrs={'class': 'form-control',"disabled":"disabled"}))
    detail = forms.CharField(widget=widgets.Textarea(attrs={'id': 'detail', 'class': 'kind-content'}))
    solution = forms.CharField(widget=widgets.Textarea(attrs={'id':'solution','class':'kind-content'}))

apps/question_record/views.py
from django.shortcuts import render
# Create your views here.
from django.shortcuts import render,redirect,HttpResponse
from .models import Ask_Question
from .forms import QuestionMaker,QuestionKill
from django.db.models import Q
from django.contrib.auth.decorators import login_required

@login_required
def show_index(request):
    current_user_id = request.user.id
    print("hahah",current_user_id)
    result = Ask_Question.objects.filter(user_id=current_user_id).order_by('status'). \
        only('title', 'status', 'ctime', 'processer')
    print("eee",result)
    return render(request,"question_record/index.html",{"result":result})

import datetime

@login_required
def create_question(request):
    if request.method == 'GET':
        form = QuestionMaker()
    else:
        form = QuestionMaker(request.POST)
        if form.is_valid():
            # title,content
            # form.cleaned_data
            dic = {}
            dic['user_id'] = request.user.id # session中获取
            dic['ctime'] = datetime.datetime.now()
            dic['status'] = 1
            dic.update(form.cleaned_data)
            print(dic,"aaa")
            Ask_Question.objects.create(**dic)
            return redirect('/questions/index/')
    return render(request, 'question_record/question_create.html',{'form':form})

@login_required
def edit_question(request,nid):

    if request.method == "GET":
        obj = Ask_Question.objects.filter(id=nid, status=1).only('id', 'title', 'detail').first()
        if not obj:
            return HttpResponse('已处理中的问题无法修改..')
        # initial 仅初始化，不会触发form.error验证错误
        form = QuestionMaker(initial={'title': obj.title,'detail': obj.detail})
        # 执行error会进行验证
        return render(request,'question_record/question_edit.html',{'form':form,'nid':nid})
    else:
        form = QuestionMaker(data=request.POST)
        user = Ask_Question.objects.filter(id=nid).first().user
        if form.is_valid() and request.user == user:
            # 就update而言，v是指受响应的行数，status=1是关键，防止多人重复更改
            v = Ask_Question.objects.filter(id=nid, status=1).update(**form.cleaned_data)
            if not v:
                return HttpResponse('问题已经被解决')
            else:
                return redirect('/questions/index/')
        return render(request, 'question_record/question_edit.html', {'form': form, 'nid': nid})

@login_required
def question_kill_list(request):
    current_user_id=request.user.id
    result=Ask_Question.objects.filter(Q(processer_id=current_user_id)|Q(status=1)).order_by("status")
    return render(request,"question_record/question_kill_list.html",{"result":result})

@login_required
def question_kill(request,nid):
    if request.method=="GET":
        v=Ask_Question.objects.filter(id=nid,status=1).update(processer_id=request.user.id,status=2) \
          or Ask_Question.objects.filter(processer_id=request.user.id,id=nid).count()#第二个filter是指过去抢到的问题处理单
        if not v:
            return HttpResponse("其他同事已经在你点击时候处理")
        obj=Ask_Question.objects.filter(id=nid).first()
        form=QuestionKill(initial={"title":obj.title,"detail":obj.detail,"solution":obj.solution})

        return render(request,"question_record/question_kill.html",{"form":form,"nid":nid,"z":obj.detail})
    else:
        #确认当前用户在做操作
        ret=Ask_Question.objects.filter(id=nid,processer_id=request.user.id,status=2).count()
        print(ret,"侧写师")
        if not ret:
            return HttpResponse("此处返还json")
        form=QuestionKill(request.POST)
        if form.is_valid():
            dic={}
            dic["status"]=3
            dic["solution"]=form.cleaned_data.get("solution")
            dic["ptime"]=datetime.datetime.now()
            Ask_Question.objects.filter(id=nid,processer_id=request.user.id,status=2).update(**dic)
            return redirect("/questions/kill-list")
        obj=Ask_Question.objects.filter(id=nid).first()
        return render(request, "question_record/question_kill.html", {"obj":obj,"form": form, "nid": nid})

templates/question_record/index.html
{% extends "base.html" %}
{% block head %}
    问题主页
{% endblock  %}

{% block content %}
    <ol class="breadcrumb" style="margin-bottom: 0;">
        <li><a href="#">问题管理</a></li>
        <li class="active">问题列表</li>
    </ol>
    <div>

        <div class="clearfix"  style="height: 36px;line-height: 35px;padding: 0 15px;border-top: 1px solid #dddddd;background-color: #f1f0f0;">
            <i class="fa fa-table" aria-hidden="true"></i>
            <a target="_blank" href="{% url "question:create_question" %}"
               style="display: inline-block;padding:0 10px;background-color: #428bca;color: #ffffff;float: right">
                <i class="fa fa-plus-circle" aria-hidden="true"></i>
                创建反馈问题
            </a>
        </div>

        <table class="table table-bordered">
            <thead>
            <tr>
                <th>问题标题</th>
                <th>状态</th>
                <th>创建时间</th>
                <th>处理人</th>
                <th>操作</th>
            </tr>
            </thead>
            <tbody>
            {% for row in result %}
                <tr>
                    <td>{{ row.title }}</td>
                    <td>{{ row.get_status_display }}</td>
                    <td>{{ row.ctime }}</td>
                    <td>{{ row.processer.username }}</td>
                    <td>
                        <a class="btn btn-danger btn-xs">
                            <i class="fa fa-times" aria-hidden="true"></i>
                            删除
                        </a>
                        |
                        <a class="btn btn-primary btn-xs" href="/questions/edit-{{ row.id }}">
                            <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                            编辑
                        </a>
                    </td>
                </tr>
            {% endfor %}

            </tbody>
        </table>
        <div class="clearfix">
            <ul class="pagination right" style="margin-top: 0">
               {{ page_str }}
            </ul>
        </div>
    </div>
{% endblock %}

templates/question_record/question_create.html
{% extends "base.html" %}
{% block head %}
    提交问题
{% endblock  %}
{% block css %}
     <link rel="stylesheet" href="/static/plugins/kindeditor/themes/default/default.css"/>
    <style>
        .kind-content {
            width: 100%;
            min-height: 400px;
        }
    </style>
{% endblock %}

{% block content %}
     <ol class="breadcrumb" style="margin-bottom: 0;">
        <li><a href="#">问题管理</a></li>
        <li class="active">创建问题</li>
    </ol>
    <div style="padding: 5px 8px;">
        <form method="POST" action="/questions/create/" novalidate >
            {% csrf_token %}
            <div class="form-group " >
                <label for="{{ form.title.id_for_label }}">标题 <span>{{ form.title.errors.0 }}</span></label>

                {{ form.title }}
            </div>
            <div class="form-group" >
                <label for="detail">内容 <span>{{ form.detail.errors.0 }}</span></label>

                    {{ form.detail }}

            </div>

            <div class="form-group">
                <input type="submit" class="btn btn-primary" value="保 存">
            </div>
        </form>
    </div>
{% endblock %}

{% block js %}
    <script charset="utf-8" src="/static/plugins/kindeditor/kindeditor-min.js"></script>
    <script charset="utf-8" src="/static/plugins/kindeditor/lang/zh_CN.js"></script>
    <script>
        KindEditor.ready(function (K) {
            var editor = K.create('#detail', {
                resizeType: 1
            });
        });
    </script>
{% endblock %}

templates/question_record/question_edit.html
{% extends "base.html" %}
{% block head %}
    提交问题
{% endblock  %}
{% block css %}
     <link rel="stylesheet" href="/static/plugins/kindeditor/themes/default/default.css"/>
    <style>
        .kind-content {
            width: 100%;
            min-height: 450px;
        }
    </style>
{% endblock %}

{% block content %}
     <ol class="breadcrumb" style="margin-bottom: 0;">
        <li><a href="#">问题管理</a></li>
        <li class="active">修改问题</li>
    </ol>
    <div style="padding: 5px 8px;">
        <form method="POST" action="/questions/edit-{{ nid }}/" novalidate>
            {% csrf_token %}
            <div class="form-group">
                <label for="{{ form.title.id_for_label }}">标题 <span>{{ form.title.errors.0 }}</span></label>
                {{ form.title }}
            </div>
            <div class="form-group">
                <label for="detail">内容 <span>{{ form.detail.errors.0 }}</span></label>
                {{ form.detail }}
            </div>

            <div class="form-group">
                <input type="submit" class="btn btn-primary" value="保 存">
            </div>
        </form>
    </div>
{% endblock %}

{% block js %}
    <script charset="utf-8" src="/static/plugins/kindeditor/kindeditor-min.js"></script>
    <script charset="utf-8" src="/static/plugins/kindeditor/lang/zh_CN.js"></script>
    <script>
        KindEditor.ready(function (K) {
            var editor = K.create('#detail', {
                resizeType: 1
            });
        });
    </script>
{% endblock %}

templates/question_record/question_kill.html
{% extends "base.html" %}
{% block head %}
    提交问题
{% endblock  %}
{% block css %}
     <link rel="stylesheet" href="/static/plugins/kindeditor/themes/default/default.css"/>
    <style>
        .kind-content {
            width: 100%;
            min-height: 450px;
        }
    </style>
{% endblock %}

{% block content %}
     <ol class="breadcrumb" style="margin-bottom: 0;">
        <li><a href="#">问题管理</a></li>
        <li class="active">创建问题</li>
    </ol>
    <div style="padding: 5px 8px;">
        <form method="POST" action="/questions/kill-{{ nid }}" novalidate>
            {% csrf_token %}
            <div class="form-group">
                <label for="{{ form.title.id_for_label }}">标题 <span>{{ form.title.errors.0 }}</span></label>
                {{ form.title }}
            </div>
            <div class="form-group">
                <label for="detail">问题描述 <span>{{ form.detail.errors.0 }}</span></label>
                {{ form.detail }}
            </div>

            <div class="form-group">
                <label for="detail">解决方案 <span>{{ form.solution.errors.0 }}</span></label>
                {{ form.solution }}
            </div>

            <div class="form-group">
                <input type="submit" class="btn btn-primary" value="保 存">
            </div>
        </form>
    </div>
{% endblock %}

{% block js %}
    <script charset="utf-8" src="/static/plugins/kindeditor/kindeditor-min.js"></script>
    <script charset="utf-8" src="/static/plugins/kindeditor/lang/zh_CN.js"></script>
    <script>

         KindEditor.ready(function (K) {
            var editor = K.create('#solution', {
                resizeType: 1
            });
        });
        KindEditor.ready(function (K) {
            var editor = K.create('#detail', {
                resizeType: 1,
                readonlyMode : true,
                height: '200px'
            });
        });
    </script>
{% endblock %}

templates/question_record/question_kill_list.html
{% extends "base.html" %}
{% block head %}
    问题主页
{% endblock  %}

{% block content %}
    <ol class="breadcrumb" style="margin-bottom: 0;">
        <li><a href="#">问题管理</a></li>
        <li class="active">处理问题列表</li>
    </ol>
    <div>

        <div class="clearfix"  style="height: 36px;line-height: 35px;padding: 0 15px;border-top: 1px solid #dddddd;background-color: #f1f0f0;">
            <i class="fa fa-table" aria-hidden="true"></i>

        </div>

        <table class="table table-bordered">
            <thead>
            <tr>
                <th>问题标题</th>
                <th>状态</th>
                <th>创建时间</th>
                <th>提交者</th>
                <th>操作</th>
            </tr>
            </thead>
            <tbody>
            {% for row in result %}
                <tr>
                    <td>{{ row.title }}</td>
                    <td>{{ row.get_status_display }}</td>
                    <td>{{ row.ctime }}</td>
                    <td>{{ row.user.username }}</td>
                    <td>
                        <a class="btn btn-primary btn-xs" href="/questions/kill-{{ row.id }}">
                            <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                            {% if row.status == 1 %}
                            抢单
                            {% elif row.status == 2 %}
                            处理
                            {% elif row.status == 3 %}
                                解决方案
                            {% endif %}

                        </a>
                        |
                        <a class="btn btn-danger btn-xs">
                            <i class="fa fa-times" aria-hidden="true"></i>
                            删除
                        </a>
                        |
                        <a class="btn btn-primary btn-xs" href="">
                            <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                            编辑
                        </a>
                    </td>
                </tr>
            {% endfor %}

            </tbody>
        </table>
        <div class="clearfix">
            <ul class="pagination right" style="margin-top: 0">
               {{ page_str }}
            </ul>
        </div>
    </div>
{% endblock %}