Cha_Flow/urls.py
from django.conf.urls import url,include
from django.contrib import admin
import xadmin
from Cha_Flow import views
from users import views as user_view
from workflows import views as workflow_view

urlpatterns = [
    url(r'^brain/', xadmin.site.urls),
    url(r"^questions/",include("question_record.urls",namespace="question")),
    url(r'^workflow/',include("workflows.urls",namespace="workflow")),
    url(r'^user/',include('users.urls',namespace='users')),
    url(r"^$",views.index,name="dashboard"),
    url(r"^login",user_view.acc_login,name="login"),
    url(r"^logout",user_view.acc_logout,name="logout"),


    url(r'^403.html',views.permission_denied,name='code 403'),
    url(r'^500.html',views.page_error,name='code 500')
]

# 定义错误跳转页面
handler404 = views.page_not_found
handler403 = views.permission_denied
handler500 = views.page_error

apps/users/urls.py
__author__ = 'yuchen'
__date__ = '2019/2/14 09:56'


from django.conf.urls import url,include
from users import views


urlpatterns = [
    url(r'^my_information/$',views.myself,name='my_information'),
    url(r'^edit_my_information/$',views.myself_edit,name='edit_my_information'),
    url(r'my_image/$',views.my_image,name='my_image'),
    url(r'user_info/(?P<user_id>\d+)/$',views.user_info,name='user_info')
    # url(r'^edit-my-information/$',views.myself_edit,name='edit_my_information'),
    # url(r'^my-image/$',views.my_image,name='my_image'),
]

apps/workflows/urls.py
__author__ = 'yuchen'
__date__ = '2019/1/31 11:03'


from django.conf.urls import url,include

from workflows import views


urlpatterns = [


    #提交审批申请的页面
    url(r'^add_alters/$',views.add_alters,name="add_alters"),
    #只保存审批申请的页面
    url(r'save_alters/$',views.save_alters,name="save_alters"),
    #查看已提交的变更详情
    url(r"^show_alter/(\w+)/$",views.show_alter,name="show_alter"),
    #对于被打回的或处于保存状态的变更文档进行编辑操作
    url(r'^edit_alter/(\w+)/$',views.edit_alter,name="edit_alter"),
    #对于被打回的或处于保存状态的变更文档进行删除
    url(r'delete_alter/(\w+)/$',views.delete_my_submit_alter,name='delete_my_submit_alter'),
    #对于被打回的或处于保存状态的变更文档进行内容更新并提交工作流
    url(r'update_and_submit/(\w+)/$',views.update_and_submit,name='update_and_submit'),
    #对于被打回的或处于保存状态的变更文档只进行内容更新
    url(r'update_and_save/(\w+)/$',views.update_and_save,name='update_and_save'),
    # 我提交的变更申请的列表
    url(r'^show_my_alters/$', views.show_my_submit_alter,name='show_my_alters'),
    # 具体变更的流程环节详情
    url(r'^alter_detail/(\w+)/$', views.alter_detail, name='alter_detail'),
    # 需要我审批的流程
    url(r'^my_alter_approvals/$',views.my_alter_approvals,name="my_alter_approvals"),
    #具体审批页
    url(r'^alter_approve/(\w+)/$',views.alter_approve,name='alter_approve'),
    #我的审批记录  有小bug，暂时未改
    url(r'^my_approval_records/$', views.my_approval_records,name='my_approval_records'),
    # 提交的变更的实时流程态
    url(r'^alter_flow_real_time/(\w+)/$',views.alter_flow_real_time,name="alter_flow_real_time")






]

extra_apps/DjangoUeditor/urls.py
# coding:utf-8
from django import VERSION
from .widgets import UEditorWidget, AdminUEditorWidget
from .views import get_ueditor_controller
from django.conf.urls import url

urlpatterns = [
    url(r'^controller/$', get_ueditor_controller),
]

apps/workflows/models.py
from django.db import models

# Create your models here.


from django.db import models
from  users.models import UserProfile
from shortuuidfield import ShortUUIDField
# Create your models here.



class FlowTemplate(models.Model):
    """流程模版，具备扩展性"""
    name = models.CharField(max_length=128, unique=True)
    description = models.TextField(blank=True, null=True)
    flow_type_choices = (('Alter', '变更流程'),)
    flow_type = models.CharField(choices=flow_type_choices, max_length=64)

    def __str__(self):
        return self.name


class Alter_Desc(models.Model):
    alter = models.ForeignKey("Alter",default=None)
    alter_momo =models.CharField("变更内容概括",max_length=255)

    change_type = models.SmallIntegerField(choices=((0, "功能优化"), (1, "问题修复"), (2, "数据调整"),(3,'测试环境调整'),(4,'数据导入导出')), verbose_name="修改类型")
    approve_user = models.CharField(max_length=128, verbose_name="提出人")
    alter_description = models.TextField("详细说明", blank=True, null=True)
    other_env = models.CharField(max_length=256,verbose_name="涉及环境")

    def __str__(self):
        return self.alter_momo



class Alter(models.Model):
    """流程总表，存储所有流程都会有的公共信息"""
    alter_id = ShortUUIDField(primary_key=True)
    template = models.ForeignKey(FlowTemplate,default=0)
    alter_title=models.CharField(max_length=255,verbose_name="变更名称")
    proposer = models.ForeignKey(UserProfile,verbose_name="变更申请人",default=None,related_name="proposer_alters")
    operator = models.ForeignKey(UserProfile,verbose_name="变更操作人",default=None,related_name="operator_alters")
    # content = models.TextField(blank=True,null=True,verbose_name="申请内容")
    in_queue = models.BooleanField(default=True,help_text="只要任务没被人处理，就会一直在queue中")
    start_time = models.DateTimeField("开始时间")
    end_time = models.DateTimeField("结束时间")
    date = models.DateTimeField(auto_created=True,auto_now=True,verbose_name="创建时间")
    risk_level = models.SmallIntegerField(choices=((0,"低"), (1,"中"), (2,"高")),verbose_name="风险等级")
    alter_type_choice = ((0, "一般变更"), (1, "紧急变更"),(2,"特急变更"))
    alter_type = models.SmallIntegerField(choices=alter_type_choice,verbose_name="变更类型",default=None)
    memo = models.TextField('备注', blank=True, null=True, default=None)

    alter_effect = models.SmallIntegerField(choices=((0, "无影响"), (1, "业务中断")), verbose_name="业务影响",default=0)
    alter_stop_time = models.CharField(max_length=128,verbose_name="业务中断时间",default=None)
    alter_stop_range = models.CharField(max_length=128,verbose_name="业务中断范围",default=None)
    technical_director = models.ForeignKey(UserProfile, verbose_name="团队技术负责人", related_name="technical_director_alters",default=None)
    customer_director = models.ForeignKey(UserProfile, verbose_name="团队技术负责人",related_name="customer_director_alters",default=None)

    technical_director_opnion = models.TextField(max_length=500,verbose_name="团队技术负责人意见",default=None)
    committee_opnion = models.TextField(max_length=500,verbose_name="方案评审会评审意见",default=None)

    implement_plan = models.TextField(max_length=500, verbose_name="实施方案", default=None)
    implement_plan_time = models.CharField(max_length=128, verbose_name="实施方案预期耗时", default=None)
    implement_validate_plan = models.TextField(max_length=500, verbose_name="实施后验证方案", default=None)
    implement_validate_plan_time = models.CharField(max_length=128, verbose_name="实施后验证方案预期耗时", default=None)

    back_plan =  models.TextField(max_length=500,verbose_name="回退方案",default=None)
    back_plan_time = models.CharField(max_length=128, verbose_name="回退方案预期耗时",default=None)
    back_validate_plan = models.TextField(max_length=500, verbose_name="应急处理后验证方案",default=None)
    back_validate_plan_time = models.CharField(max_length=128, verbose_name="处理后预期耗时",default=None)

    yingji_plan = models.TextField(max_length=500, verbose_name="应急预案", default=None)
    yingji_plan_time = models.CharField(max_length=128, verbose_name="应急预案预期耗时", default=None)
    yingji_validate_plan = models.TextField(max_length=500, verbose_name="回退后验证方案", default=None)
    yingji_validate_plan_time = models.CharField(max_length=128, verbose_name="回退后验证方案预期耗时", default=None)
    alter_status_choice = ((0,"已提交"),(1,"保存未提交"),(2,"被打回"),(3,"流程完成"))
    alter_status = models.SmallIntegerField(choices=alter_status_choice,verbose_name="变更状态",default=0)



    def __str__(self):
        return "变更名称:%s 发起人:%s" %(self.alter_title,self.proposer)





class Step(models.Model):
    """流程的每个环节"""
    flow_template = models.ForeignKey("FlowTemplate", verbose_name="所属流程")
    name = models.CharField("环节名称",max_length=128)
    description = models.TextField("环节介绍",blank=True,null=True)
    #order 的目的是用来用int格式来记录所处的流程状态，我的设计思路是，可以有n个order，只要你想。通过order的大小数值来记录顺序
    order = models.PositiveSmallIntegerField("环节步骤")
    role = models.ForeignKey("FlowRole",verbose_name="审批角色")
    is_countersign =  models.BooleanField("会签环节",default=False)
    required_polls = models.PositiveSmallIntegerField("会签最少需同意的人数",blank=True,null=True)


    def __str__(self):
        return "环节:%s 状态:%s" %(self.name,self.order)

    class Meta:
        unique_together = ("flow_template",'order')


class FlowRecord(models.Model):
    """流程的流转记录"""
    flow = models.ForeignKey("Alter",default=None)
    step = models.ForeignKey("Step")
    step_status_choice = ((0, "环节未开始"), (1, "环节已结束"))
    step_status = models.SmallIntegerField(choices=step_status_choice, verbose_name="当前环节状态", default=0)
    user = models.ForeignKey(UserProfile,verbose_name="审批用户",blank=True,null=True)
    status_choices = ((0,'同意'),(1,'拒绝'),(2,'需额外审批人审批'),(3,'待处理'))
    status = models.SmallIntegerField(choices=status_choices,verbose_name="审批状态")
    comment = models.TextField(max_length=1024, verbose_name="审批意见",default=None,null=True,blank=True)
    extra_parties = models.ManyToManyField(UserProfile,verbose_name="额外审批人列表",
                                           related_name="related_parties",
                                           blank=True)
    date = models.DateTimeField("添加时间",auto_now=True)


    def __str__(self):
        return "%s:%s" %(self.step,self.get_status_display())


class FlowRole(models.Model):
    """流程角色"""
    name = models.CharField(max_length=64,unique=True)
    users = models.ManyToManyField(UserProfile,blank=True)
    is_dynamic_role = models.BooleanField(default=False)
    role_lookup_func = models.CharField("查找动态role的函数",max_length=64,blank=True,null=True)

    def __str__(self):
        return self.name

apps/workflows/forms.py
__author__ = 'yuchen'
__date__ = '2019/1/31 11:03'

#_*_coding:utf-8_*_

from django import forms
from django.forms import widgets
from users import models

class ApprovalForm(forms.Form):
    comment = forms.CharField(label="你的审批意见",widget=forms.Textarea(attrs={'class': "form-control"}))
    status_choices = ((0, '同意'), (1, '拒绝'))
    status = forms.IntegerField(label="审批结果",widget=forms.widgets.Select(choices=status_choices,attrs={'class': "form-control"}))



class AlterMaker(forms.Form):
    alter_title = forms.CharField(label="变更标题",max_length=128,widget=widgets.TextInput(attrs={'class': 'form-control'}))
    operator = forms.IntegerField(label="变更操作人",widget=widgets.Select(attrs={'class': 'form-control  select2' }))
    start_time = forms.DateTimeField()
    end_time = forms.DateTimeField()
    risk_level=forms.IntegerField(label="风险等级",widget=forms.widgets.Select(choices=((0,"低"), (1,"中"), (2,"高")),attrs={'class': 'form-control'}))
    alter_type=forms.IntegerField(label="变更类型",widget=forms.widgets.Select(choices=((0, "普通变更"), (1, "紧急变更"),(2,"特急变更")),attrs={'class': 'form-control'}))
    memo = forms.CharField(label="备注",widget=widgets.TextInput(attrs={'class':'form-control','placeholder':'备注信息可以不填'}),required=False)

    alter_momo = forms.CharField(label="变更内容概括",widget=widgets.Textarea(attrs={'class': 'form-control',"rows":"3"}))
    change_type = forms.IntegerField(label="修改类型", widget=forms.widgets.Select(choices=((0, "功能优化"), (1, "问题修复"), (2, "数据调整"),(3,'测试环境调整'),(4,'数据导入导出')),attrs={'class': 'form-control select2'}))
    approve_user = forms.CharField(label="提出人",max_length=128, widget=widgets.TextInput(attrs={'class': 'form-control'}))
    alter_description = forms.CharField(label="详细说明",widget=widgets.Textarea(attrs={'id': 'detail', 'class': 'kind-content'}))
    other_env = forms.CharField(label="涉及环境",max_length=128,widget=widgets.TextInput(attrs={'class': 'form-control'}))

    alter_effect = forms.IntegerField(label="业务影响",widget=forms.widgets.Select(choices=((0, "无影响"), (1, "业务中断")),
                                                                attrs={'class': 'form-control'}))
    alter_stop_time = forms.CharField(label="业务中断时间", max_length=128,
                                  widget=widgets.TextInput(attrs={'class': 'form-control',"placeholder":"如果没有，请填写无"}))
    alter_stop_range = forms.CharField(label="业务中断范围", max_length=128,
                                      widget=widgets.TextInput(attrs={'class': 'form-control',"placeholder":"如果没有，请填写无"}))
    technical_director = forms.IntegerField(label="团队技术负责人", widget=widgets.Select(attrs={'class': 'form-control  select2'}))
    customer_director = forms.IntegerField(label="客户负责人", widget=widgets.Select(attrs={'class': 'form-control  select2'}))

    technical_director_opnion = forms.CharField(label="团队技术负责人意见",widget=widgets.Textarea(attrs={'class': 'form-control',"rows":"2"}))
    committee_opnion = forms.CharField(label="方案评审会评审意见",widget=widgets.Textarea(attrs={'class': 'form-control', "rows": "2"}))

    implement_plan = forms.CharField(label="实施方案", max_length=500, widget=widgets.TextInput(attrs={'class': 'form-control'}))
    implement_plan_time = forms.CharField(label="实施方案预计耗时", max_length=128,widget=widgets.TextInput(attrs={'class': 'form-control'}))
    implement_validate_plan = forms.CharField(label="实施后验证方案", max_length=500,widget=widgets.TextInput(attrs={'class': 'form-control'}))
    implement_validate_plan_time = forms.CharField(label="实施后预计耗时", max_length=128,widget=widgets.TextInput(attrs={'class': 'form-control'}))

    back_plan = forms.CharField(label="回退方案",max_length=500,widget=widgets.TextInput(attrs={'class': 'form-control'}))
    back_plan_time = forms.CharField(label="回退方案预计耗时",max_length=128,widget=widgets.TextInput(attrs={'class': 'form-control'}))
    back_validate_plan = forms.CharField(label="回退后验证方案", max_length=500, widget=widgets.TextInput(attrs={'class': 'form-control'}))
    back_validate_plan_time = forms.CharField(label="回退后预计耗时", max_length=128,widget=widgets.TextInput(attrs={'class': 'form-control'}))

    yingji_plan = forms.CharField(label="应急预案",max_length=500,widget=widgets.TextInput(attrs={'class': 'form-control','placeholder':'应急预案可以不填'}),required=False)
    yingji_plan_time = forms.CharField(label="应急预案预期耗时",max_length=128,widget=widgets.TextInput(attrs={'class': 'form-control','placeholder':'可以不填'}),required=False)
    yingji_validate_plan= forms.CharField(label="应急处理后验证方案", max_length=500, widget=widgets.TextInput(attrs={'class': 'form-control','placeholder':'应急处理后验证方案可以不填'}),required=False)
    yingji_validate_plan_time = forms.CharField(label="验证方案预期耗时", max_length=128,widget=widgets.TextInput(attrs={'class': 'form-control','placeholder':'可以不填'}),required=False)

    def __init__(self, *args, **kwargs):
        super(AlterMaker, self).__init__(*args, **kwargs)
        self.fields['operator'].widget.choices = models.UserProfile.objects.all().values_list('id','username')
        self.fields['technical_director'].widget.choices = models.UserProfile.objects.all().values_list('id', 'username')
        self.fields['customer_director'].widget.choices = models.UserProfile.objects.all().values_list('id', 'username')

templates/workflow/alter_approve.html
{% extends 'base.html' %}
{% load alterflow_tags %}

{% block head %}
  审批页
{% endblock %}

{% block content %}
    <ol class="breadcrumb" style="margin-bottom: 0;">
        <li><a href="#" style="font-size: large">变更管理</a></li>
        <li class="active" style="font-size: large">需要我审批的流程</li>
        <li class="active" style="font-size: large">审批页面</li>
    </ol>

    <div class="panel">
        <div class="panel-heading">
            <h3 ><a href="{% url 'workflow:show_alter' flow_record_objective.flow.alter_id %}">{{ flow_record_objective.flow }}</a></h3>
        </div>

        <!-- Striped Table -->
        <!--===================================================-->
        <div class="panel-body">
            <div class="table-responsive">
                <table class="table table-striped table-hover">
                    {% get_flow_records flow_record_objective as flow_record_objectives %}
                    <thead>
                        <tr>
                            <td>环节</td>
                            <td>环节名称</td>
                            <td>审批人</td>
                            <td>审批意见</td>
                            <td>审批结果</td>
                            <td>审批日期</td>
                        </tr>
                    </thead>
                    <tbody>
                        {% for record_obj in flow_record_objectives   %}
                        <tr>
                            <td>{{ record_obj.step.order }}</td>
                            <td>{{ record_obj.step.name }}</td>
                            <td>
                            {% if record_obj.user %}
                                <a href="{% url 'users:user_info' record_obj.user.id %}">{{ record_obj.user }}</a>
                            {% else %}
                                当前操作者
                            {% endif %}

                            </td>
                            <td>{{ record_obj.comment|default:"正在撰写" }}</td>
                            <td>{{ record_obj.get_status_display }}</td>
                            <td>{% if record_obj.user %}
                                    {{ record_obj.date }}
                                {% endif %}
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>

                </table>
            </div>

            <form class="form" method="post">{% csrf_token %}
                <div class="row">
                    <div class="col-md-12">
                    <h3>{{ flow_record_objective}}</h3>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        {{ form.comment.label }}
                        {{ form.comment }}
                    </div>
                    <div class="col-md-4" style="margin-top:20px">
                            {{ form.status.label }}
                            {{ form.status }}

                    </div>
                    <div class="col-lg-12" style="margin-top:20px">
                            <input type="submit" class="btn btn-success">
                    </div>


                </div>

            </form>

        </div>


    </div>


{% endblock %}

templates/workflow/alter_flow_real_time.html
{% extends 'base.html' %}
{% load alterflow_tags %}

{% block head %}
  审批页
{% endblock %}

{% block content %}
    <ol class="breadcrumb" style="margin-bottom: 0;">
        <li><a href="#" style="font-size: large">变更管理</a></li>
        <li class="active" style="font-size: large">变更所处状态</li>
    </ol>

    <div class="panel">
        <div class="panel-heading">
            <h3 ><a href="{% url 'workflow:show_alter' flow_record_objective.flow.alter_id %}">{{ flow_record_objective.flow }}</a></h3>
        </div>

        <!-- Striped Table -->
        <!--===================================================-->
        <div class="panel-body">
            <div class="table-responsive">
                <table class="table table-striped table-hover">
                    {% get_flow_records flow_record_objective as flow_record_objectives %}
                    <thead>
                        <tr>
                            <td>环节</td>
                            <td>环节名称</td>
                            <td>审批人</td>
                            <td>审批意见</td>
                            <td>审批结果</td>
                            <td>审批日期</td>
                        </tr>
                    </thead>
                    <tbody>
                        {% for record_obj in flow_record_objectives   %}
                        <tr>
                            <td>{{ record_obj.step.order }}</td>
                            <td>{{ record_obj.step.name }}</td>
                            <td>
                                {% if record_obj.user %}
                                    <a href="{% url 'users:user_info' record_obj.user.id %}">{{ record_obj.user }}</a>
                                {% else %}
                                    等待中
                                {% endif %}


                            </td>
                            <td>{{ record_obj.comment|default:"等待中" }}</td>
                            <td>{{ record_obj.get_status_display }}</td>
                            <td>{% if record_obj.user %}
                                    {{ record_obj.date }}
                                {% endif %}
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>

                </table>
            </div>

        </div>


    </div>


{% endblock %}

templates/workflow/flow_detail.html
{% extends "base.html" %}
{% load alterflow_tags %}

{% block head %}
    变更所处流程详情
{% endblock %}

{% block content %}
    <ol class="breadcrumb" style="margin-bottom: 0;">
        <li><a href="#" style="font-size: large">变更管理</a></li>
        <li class="active" style="font-size: large">变更所处流程详情</li>
    </ol>
    <div class="panel">
        <div class="panel-heading">
            <h3 class="panel-title">{{ flow_obj }}</h3>
        </div>

        <!-- Striped Table -->
        <!--===================================================-->
        <div class="panel-body">
            <div class="table-responsive">
                <table class="table table-striped table-hover">
                    <thead>
                        <tr>
                            <th>环节</th>
                            <th>审批人</th>

                            <th>审批人意见</th>
                            <th>审批时间</th>
                            <th>审批状态</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for step_record in flow_obj.flowrecord_set.all %}
                        <tr>
                            <td>{{ step_record.step }}</td>
                            <td>{% if step_record.user %}
                                    <a href="{% url 'users:user_info' step_record.user.id %}">{{ step_record.user }}</a>
                                {% else %}
                                    暂未审批
                                {% endif %}</td>
                            <td>{% if step_record.comment %}{{ step_record.comment }}{% else %}暂无{% endif %}</td>
                            <td>{{ step_record.date }}</td>
                            <td>{{ step_record.get_status_display }}</td>

                            <td>{{ obj.date }}</td>
                            <td></td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

templates/workflow/my_alter_approvals.html
{% extends "base.html" %}
{% load alterflow_tags %}

{% block head %}
    需要我审批的流程
{% endblock  %}

{% block content %}
    <ol class="breadcrumb" style="margin-bottom: 0;">
        <li><a href="#" style="font-size: large">变更管理</a></li>
        <li class="active" style="font-size: large">需要我审批的流程</li>
    </ol>
     <div class="panel">
        <div class="panel-heading">
            <h3 class="panel-title">{{ flow_obj }}</h3>
        </div>

        <!-- Striped Table -->
        <!--===================================================-->
        <div class="panel-body">
            <div class="table-responsive">
                <table class="table table-striped table-hover">
                    <thead>
                        <tr>
                            <th>变更名称</th>

                            <th>当前步骤</th>
                            <th>发起时间</th>
                            <th>申请人</th>

                            <th>变更详情</th>
                            {% if queue_flow.step.order != 1 %}
                            <th>上一环节审批人</th>
                            <th>上一环节审批意见</th>
                            <th>上一环节审批结果</th>
                            <th>上一环节审批时间</th>
                            {% endif %}
                            <th>当前状态</th>
                            <th>审批</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% if queued_flows %}
                            {% for flow_record in queued_flows  %}
                                {% get_last_step_obj flow_record as last_step_record_obj %}

                                <tr>
                                    <td>{{ flow_record.flow.alter_title }}</td>

                                    <td>{{ flow_record }}</td>
                                    <td>{{ flow_record.flow.date }}</td>
                                    <td><a href="{% url 'users:user_info' flow_record.flow.proposer.id %}">{{ flow_record.flow.proposer }}</a></td>

                                    <td ><a href="{% url 'workflow:show_alter' flow_record.flow.alter_id %}"><i style="cursor: pointer;color: #1c94c4" class="fa fa-fw fa-file-word-o " aria-hidden="true"></i></a></td>
                                    {% if queue_flow.step.order != 1 %}
                                    <td class="btn-info"> <a style="color: white" href="{% url 'users:user_info' last_step_record_obj.user.id %}">{{ last_step_record_obj.user }}</a></td>
                                    <td class="btn-info">{{ last_step_record_obj.comment }}</td>
                                    <td class="btn-info">{{ last_step_record_obj.get_status_display }}</td>
                                    <td class="btn-info">{{ last_step_record_obj.date }}</td>
                                    {% endif %}

                                    <td>{{ flow_record.get_status_display }}</td>

                                    <td><a href="{% url "workflow:alter_approve" flow_record.id %}"><i style="cursor: pointer;color: #1c94c4" class="fa fa-pencil-square-o " aria-hidden="true"></i></a></td>
                                </tr>
                            {% endfor %}
                        {% else %}
                            <tr><td style="text-align: center" colspan="10"><span style="font-size: 20px">当前无需要审批的流程!</span></td></tr>
                        {% endif %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

templates/workflow/my_submit_alterlist.html
{% extends "base.html" %}
{% load alterflow_tags %}

{% block head %}
    我创建的变更
{% endblock %}

{% block content %}
    <ol class="breadcrumb" style="margin-bottom: 0;">
        <li><a href="#" style="font-size: large">变更管理</a></li>
        <li class="active" style="font-size: large">我创建的所有变更</li>
    </ol>
    <div>

        <div class="clearfix"
             style="height: 36px;line-height: 35px;padding: 0 15px;border-top: 1px solid #dddddd;background-color: #f1f0f0;">
            <i class="fa fa-table" aria-hidden="true"></i>
            <a href="{% url "workflow:add_alters" %}"
               style="display: inline-block;padding:0 10px;background-color: #428bca;color: #ffffff;float: right">
                <i class="fa fa-plus-circle" aria-hidden="true"></i>
                创建变更流程
            </a>
        </div>

        <table class="table table-bordered">
            <thead>
            <tr>
                <th>变更ID</th>
                <th>变更标题</th>
                <th>变更状态</th>
                <th>变更操作人</th>
                <th>变更提交时间</th>
                <th>变更类型</th>
                <th>目前流程状态</th>
                <th>操作</th>
            </tr>
            </thead>
            <tbody>
            {% if result %}
                {% for row in result %}
                    <tr>
                        <td>{{ row.alter_id }}</td>
                        <td>{{ row.alter_title }}</td>
                        <td>{{ row.get_alter_status_display }}</td>
                        <td><a href="{% url 'users:user_info' row.operator.id %}">{{ row.operator.username }}</a></td>
                        <td>{{ row.date }}</td>
                        <td>{{ row.get_alter_type_display }}</td>
                        {% if row.flowrecord_set.last %}
                            <td><a class="btn-link" href="{% url 'workflow:alter_detail' row.alter_id %}">
                                {% get_flow_status row %}
                            </a></td>
                        {% else %}
                            <td>暂无已记录的提交流程</td>
                        {% endif %}
                        <td>

                            <a class="btn btn-primary btn-xs" href="{% url 'workflow:show_alter' row.alter_id %}">
                                <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                                查看变更详情
                            </a>
                        </td>
                    </tr>
                {% endfor %}
            {% else %}
                <tr>
                    <td style="text-align: center" colspan="10"><span style="font-size: 20px">当前未提交变更流程!</span></td>
                </tr>
            {% endif %}

            </tbody>
        </table>
        <div class="clearfix">
            <ul class="pagination right" style="margin-top: 0">
                {{ page_str }}
            </ul>
        </div>
    </div>
{% endblock %}