Cha_Flow/urls.py
from django.conf.urls import url,include
from django.contrib import admin
import xadmin
from Cha_Flow import views
from users import views as user_view
from workflows import views as workflow_view

urlpatterns = [
    url(r'^brain/', xadmin.site.urls),
    url(r"^questions/",include("question_record.urls",namespace="question")),
    url(r'^workflow/',include("workflows.urls",namespace="workflow")),
    url(r'^user/',include('users.urls',namespace='users')),
    url(r"^$",views.index,name="dashboard"),
    url(r"^login",user_view.acc_login,name="login"),
    url(r"^logout",user_view.acc_logout,name="logout"),


    url(r'^403.html',views.permission_denied,name='code 403'),
    url(r'^500.html',views.page_error,name='code 500')
]

# 定义错误跳转页面
handler404 = views.page_not_found
handler403 = views.permission_denied
handler500 = views.page_error

apps/users/urls.py
__author__ = 'yuchen'
__date__ = '2019/2/14 09:56'


from django.conf.urls import url,include
from users import views


urlpatterns = [
    url(r'^my_information/$',views.myself,name='my_information'),
    url(r'^edit_my_information/$',views.myself_edit,name='edit_my_information'),
    url(r'my_image/$',views.my_image,name='my_image'),
    url(r'user_info/(?P<user_id>\d+)/$',views.user_info,name='user_info')
    # url(r'^edit-my-information/$',views.myself_edit,name='edit_my_information'),
    # url(r'^my-image/$',views.my_image,name='my_image'),
]

extra_apps/DjangoUeditor/urls.py
# coding:utf-8
from django import VERSION
from .widgets import UEditorWidget, AdminUEditorWidget
from .views import get_ueditor_controller
from django.conf.urls import url

urlpatterns = [
    url(r'^controller/$', get_ueditor_controller),
]

apps/users/models.py
# Create your models here.

from datetime import datetime
from django.db import models
from django.contrib.auth.models import (
    BaseUserManager, AbstractBaseUser,Group,PermissionsMixin
)
import django
from django.contrib.auth.models import AbstractUser



class Role(models.Model):
    '''角色表'''
    name = models.CharField(max_length=64,unique=True)
    #一个角色可以访问多个菜单，一个菜单可以被多个角色访问
    menus = models.ManyToManyField('Menus',blank=True,verbose_name='动态菜单')

    def __str__(self):
        return self.name


class Menus(models.Model):
    '''动态菜单'''
    name = models.CharField(max_length=64)
    # 绝对url和动态url
    url_type_choices = ((0, 'absolute'), (1, 'dynamic'))
    url_type = models.SmallIntegerField(choices=url_type_choices, default=0)
    url_name = models.CharField(max_length=128)

    def __str__(self):
        return self.name
    class Meta:
        unique_together = ('name', 'url_name')
    class Meta:
        verbose_name = '角色网址'
        verbose_name_plural = verbose_name


class UserProfile(AbstractUser):
    postion = models.CharField(max_length=100,verbose_name='职位',blank=True,null=True,default="")
    company=models.CharField(max_length=100,verbose_name="公司",blank=True,null=True,default="")
    department=models.CharField(max_length=50,verbose_name="所属团队",blank=True,null=True,default="")
    mobile=models.CharField(max_length=11,null=False,blank=True,verbose_name="联系电话",default="")
    memo = models.TextField('备注', blank=True, null=True, default=None)
    valid_begin_time = models.DateTimeField("使用权限开始日期",default=django.utils.timezone.now)
    valid_end_time = models.DateTimeField("使用权限结束日期(可以不设置)",blank=True, null=True)
    photo = models.ImageField('个人头像',blank=True,help_text="为了节省存储资源，图片采取了字节流的方式保存在数据库中,在这里上传无法生效")
    class Meta:
        verbose_name='用户信息'
        verbose_name_plural=verbose_name
        permissions = (
            ('crm_table_list', '可以查看每张表里所有的数据'),
            ('crm_table_list_view', '可以访问表里每条数据的修改页'),
            ('crm_table_list_change', '可以对表里的每条数据进行修改'),
            ('crm_table_obj_add_view', '可以访问每张表的数据增加页'),
            ('crm_table_obj_add', '可以对每张表进行数据添加'),
        )
    def __str__(self):
        return self.username

    # class Meta:
    #     permissions = (
    #         ('crm_table_list', '可以查看每张表里所有的数据'),
    #         ('crm_table_list_view', '可以访问表里每条数据的修改页'),
    #         ('crm_table_list_change', '可以对表里的每条数据进行修改'),
    #         ('crm_table_obj_add_view', '可以访问每张表的数据增加页'),
    #         ('crm_table_obj_add', '可以对每张表进行数据添加'),
    #
    #     )

apps/users/forms.py
__author__ = 'yuchen'
__date__ = '2019/2/14 11:34'


from django import forms
from django.forms import widgets

#编辑用户信息的表单
class EditUserForm(forms.Form):
    postion = forms.CharField(required=False,label="工作职位",widget=widgets.TextInput(attrs={'class':'form-control'}))
    email = forms.EmailField(required=False,label="邮箱",widget=widgets.EmailInput(attrs={'class': 'form-control'}))
    mobile = forms.CharField(required=False,label="电话",widget=widgets.TextInput(attrs={'class':'form-control'}))
    company = forms.CharField(required=False,label="公司",widget=widgets.TextInput(attrs={'class':'form-control'}))
    department = forms.CharField(required=False,label="所属团队",widget=widgets.TextInput(attrs={'class':'form-control'}))
    memo = forms.CharField(required=False,label="个人简介",widget=widgets.Textarea(attrs={'class': 'form-control',"rows":"3"}))

#重置密码的表单
class ChangePwdForm(forms.Form):
    '''重置密码'''
    old_password = forms.CharField(required=True,min_length=5,max_length=99)
    password1 = forms.CharField(required=True, min_length=5,max_length=99)
    password2 = forms.CharField(required=True, min_length=5,max_length=99)

apps/users/views.py
# Create your views here.
import django
from django.shortcuts import render,redirect,get_object_or_404,reverse
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.backends import ModelBackend
from django.contrib.auth.decorators import login_required
from .models import UserProfile
from django.db.models import Q
from . import permissions
from Cha_Flow.utils import restful
from django.views.generic import View
from django.contrib.auth.hashers import make_password
from .forms import ChangePwdForm,EditUserForm

#设置账户登录可以以用户名或者邮箱
class CustomBackend(ModelBackend):
    def authenticate(self, username=None, password=None, **kwargs):
        try:
            user = UserProfile.objects.get(Q(username=username) | Q(email=username))
            # user = UserProfile.objects.get(Q(username=username) | Q(email=username))
            if user.check_password(password):
                return user
        except Exception as e:
            return None

#登录
# @permissions.check_permission
def acc_login(request):
    if request.method == "POST":
        username = request.POST.get('email')
        password = request.POST.get('password')
        print(username,password)
        user = authenticate(username=username,password=password)
        print(user)

        if user is not None:
            if user.valid_end_time: #设置了end time
                if django.utils.timezone.now() > user.valid_begin_time and django.utils.timezone.now()  < user.valid_end_time:
                    login(request,user)
                    request.session.set_expiry(60*24*60*7)
                    #print 'session expires at :',request.session.get_expiry_date()
                    return redirect('/')
                else:
                    return render(request,'login.html',{'login_err': '账户没有权限，请联系it部门'})
            elif django.utils.timezone.now() > user.valid_begin_time:
                    login(request,user)
                    request.session.set_expiry(60*60*24*7)
                    return redirect('/')

        else:
            return render(request,'login.html',{'login_err': '用户名或者密码错误'})
    else:
        return render(request, 'login.html')

#登出
def acc_logout(request):
    logout(request)
    return redirect('/login/')


def myself(request):
    user_count = get_object_or_404(UserProfile,id=request.user.id)
    return render(request,'user/my_self_page.html',{ 'user':user_count })



def myself_edit(request):
    if request.method == "GET":
        user = get_object_or_404(UserProfile, id=request.user.id)
        form = EditUserForm(initial={'postion':user.postion,'email':user.email,'mobile':user.mobile,
                                     'memo':user.memo,'company':user.company,'department':user.department})

        return render(request,'user/edit_my_information.html',{'form':form })
    else:
        form = EditUserForm(request.POST)
        if form.is_valid():
            UserProfile.objects.filter(id=request.user.id).update(**form.cleaned_data)
            return redirect(reverse("users:my_information"))



def user_info(request,user_id):
    user = get_object_or_404(UserProfile,id=user_id)
    return render(request,'user/user_info.html',{'user':user})




#图片剪贴器
def my_image(request):
    if request.method == 'POST':
        img=request.POST['img']
        userinfo = UserProfile.objects.get(id=request.user.id)
        userinfo.photo= img
        userinfo.save()
        return restful.success()
    else:
        return render(request,'user/imagecrop.html')



class ChangepwdView(View):
    def post(self,request):
        change_pwd_form=ChangePwdForm(request.POST)
        if change_pwd_form.is_valid():
            pwd1=change_pwd_form.cleaned_data.get('password1')
            pwd2=change_pwd_form.cleaned_data.get('password2')
            email=request.POST.get('email','')
            active_code = request.POST.get('active_code')
            active_code = EmailVerifyRecord.objects.filter(code=active_code).first()

            if pwd1!=pwd2:
                return render(request,'password_reset.html',{'msg':'密码不一致','email':email})

            if active_code.email == email:
                user=UserProfile.objects.get(email=email)
                user.password=make_password(pwd1)
                user.save()
                return render(request, 'login.html')
            else:
                return render(request,'password_reset.html',{'msg':'邮箱内激活链接无效'})

        else:
            email=request.POST.get('email','')
            active_code = request.POST.get('active_code')
            return render(request,'password_reset.html',{'email':email,'change_pwd_form':change_pwd_form,'active_code':active_code})

templates/user/edit_my_information.html
{% extends "base.html" %}
{% load staticfiles %}
{% block head %}
    查看个人信息
{% endblock %}
{% block css %}

    <style>
        .kind-content {
            width: 100%;
            min-height: 200px;
        }
    </style>
{% endblock %}

{% block content %}
    <ol class="breadcrumb" style="margin-bottom: 0;">
        <li><a href="#" style="font-size: large">个人中心</a></li>
        <li class="active" style="font-size: large">编辑个人信息</li>
    </ol>
    <div class="col-md-6">

        <!-- Profile Image -->
        <div class="box box-primary">
            <div class="box-body box-profile">
                {% if user.photo %}
                        <img  src="{{ user.photo | striptags }}" class="profile-user-img img-responsive img-circle"
                             id="my_photo" name="user_face" alt="User profile picture">
                    {% else %}
                        <img  name="user_face" src="{% static '/img/evelyn.png' %}"
                             class="profile-user-img img-responsive img-circle"
                             id="my_photo" alt="User profile picture">
                    {% endif %}

                <h3 class="profile-username text-center">{{ user.username }}</h3>
                <ul class="list-group ">
                    <li class="list-group-item">
                        <form method="post" action="{% url 'users:edit_my_information' %}">
                            <b>工作职位</b>
                            <div class="form-group">
                                {{ form.postion }}
                            </div>
                            <b>邮箱(填写邮箱后也可作为登录账号)</b>
                            <div class="form-group">
                                {{ form.email }}
                            </div>
                            <b>联系电话</b>
                            <div class="form-group">
                                {{ form.mobile }}
                            </div>
                            <b>公司</b>
                            <div class="form-group">
                                {{ form.company }}
                            </div>
                            <b>所属团队</b>
                            <div class="form-group">
                                {{ form.department }}
                            </div>
                            <b>自我介绍</b>
                            <div class="form-group">
                                {{ form.memo }}
                            </div>
                            {% csrf_token %}
                            <input type="submit" class="btn btn-success " value="提交">
                        </form>
                    </li>

                </ul>


            </div>
            <!-- /.box-body -->
        </div>
        <!-- /.box -->


        <!-- /.box -->
    </div>
    <div class="col-md-6">
        <!-- About Me Box -->
        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title">修改头像</h3>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
                <strong><i class="fa fa-book margin-r-5"></i>注意！上传头像后一定要拖动一下圆形区域，否则无法修改成功</strong>

                <div style="text-align: center; ">
                    {% if user.photo %}
                        <img style="width: 250px;height: 250px " src="{{ user.photo | striptags }}" class="img-circle"
                             id="my_photo" name="user_face">
                    {% else %}
                        <img style="width: 250px;height: 250px " name="user_face" src="{% static '/img/evelyn.png' %}"
                             class="img-circle"
                             id="my_photo">
                    {% endif %}


                </div>
                <br>
                <div style="text-align: center">
                    <button class="btn btn-primary" id="upload_image" onclick="upload_image_layer()">上传照片
                    </button>
                </div>

                <!-- /.box-body -->
            </div>


        </div>
    </div>



{% endblock %}

{% block js %}
    <script type="text/javascript" src="{% static 'common/layer.js' %}"></script>
    <script>
        function upload_image_layer() {
            layer.open({
                //content:"<p>hello world</p>",
                title: "上传头像(注意！上传头像后一定要拖动一下圆形区域，否则修改不成功)",
                area: ['650px', '600px'],
                type: 2,
                content: "{% url 'users:my_image' %}",
            });
        }
    </script>

{% endblock %}

templates/user/imagecrop.html
{% load staticfiles %}
<link rel="stylesheet" href="{% static 'common/imagecrop.css' %}">
<div class="container" style="margin-left:10px">
  <div class="imageBox">
    <div class="thumbBox"></div>
    <div class="spinner" style="display: none"></div>
  </div>
  <div class="action">
    <!-- <input type="file" id="file" style=" width: 200px">-->
    <div class="new-contentarea tc"> <a href="javascript:void(0)" class="upload-img">
      <label for="upload-file">请先选择图片...</label>
      </a>
      <input type="file" class="" name="upload-file" id="upload-file" />
    </div>
    <input type="button" id="btnCrop" class="Btnsty_peyton" value="OK">
    <input type="button" id="btnZoomIn" class="Btnsty_peyton" value="+"  >
    <input type="button" id="btnZoomOut" class="Btnsty_peyton" value="-" >
  </div>
  <div class="cropped"></div>
</div>

<script src="{% static 'js/jquery-1.11.1.min.js' %}"></script>
<script type="text/javascript" src="{% static 'common/cropbox-min.js' %}"></script>
<script type="text/javascript" src="{% static 'common/myajax.js' %}"></script>
<script type="text/javascript">

$(window).load(function() {
	var options =
	{
		thumbBox: '.thumbBox',
		spinner: '.spinner',
		imgSrc: ''
	}
	var cropper = $('.imageBox').cropbox(options);
	var img="";
	$('#upload-file').on('change', function(){
		var reader = new FileReader();
		reader.onload = function(e) {
			options.imgSrc = e.target.result;
			cropper = $('.imageBox').cropbox(options);
			getImg();
		}
		reader.readAsDataURL(this.files[0]);
		this.files = [];
		//getImg();
	})
	$('#btnCrop').on('click', function(){
	    //alert("图片上传喽");
            myajax.post({
                url: '{% url "users:my_image" %}',
                type: 'POST',
                data: {"img": img},
                success: function(data){
                    if(data['code'] == "200"){
                        parent.location.reload();
                    } else {
                        alert("抱歉，这张图片上传失败");
                    }

		},
	    });

        })

	function getImg(){
		img = cropper.getDataURL();
		$('.cropped').html('');
		$('.cropped').append('<img src="'+img+'" align="absmiddle" style="width:180px;margin-top:4px;border-radius:180px;box-shadow:0px 0px 12px #7E7E7E;"><p>180px*180px</p>');
		$('.cropped').append('<img src="'+img+'" align="absmiddle" style="width:128px;margin-top:4px;border-radius:128px;box-shadow:0px 0px 12px #7E7E7E;"><p>128px*128px</p>');
		$('.cropped').append('<img src="'+img+'" align="absmiddle" style="width:64px;margin-top:4px;border-radius:64px;box-shadow:0px 0px 12px #7E7E7E;" ><p>64px*64px</p>');
		}

	$(".imageBox").on("mouseup",function(){
 		getImg();
  		});

	$('#btnZoomIn').on('click', function(){
		cropper.zoomIn();
	});
	$('#btnZoomOut').on('click', function(){
		cropper.zoomOut();
	})
});
</script>

templates/user/my_self_page.html
{% extends "base.html" %}
{% load staticfiles %}
{% block head %}
    查看个人信息
{% endblock %}
{% block css %}

    <style>
        .kind-content {
            width: 100%;
            min-height: 200px;
        }
    </style>
{% endblock %}

{% block content %}
    <ol class="breadcrumb" style="margin-bottom: 0;">
        <li><a href="#" style="font-size: large">个人中心</a></li>
        <li class="active" style="font-size: large">查看个人信息</li>
    </ol>
    <div class="col-md-6">

        <!-- Profile Image -->
        <div class="box box-primary">
            <div class="box-body box-profile">
                {% if user.photo %}
                    <img src="{{ user.photo | striptags }}" class="profile-user-img img-responsive img-circle"
                         id="my_photo" name="user_face" alt="User profile picture">
                {% else %}
                    <img name="user_face" src="{% static '/img/evelyn.png' %}"
                         class="profile-user-img img-responsive img-circle"
                         id="my_photo" alt="User profile picture">
                {% endif %}



                <h3 class="profile-username text-center">{{ user.username }}</h3>

                <p class="text-muted text-center">{{ user.postion }}</p>

                <ul class="list-group list-group-unbordered">
                    <li class="list-group-item">
                        <b>邮箱(填写邮箱后也可作为登录账号)</b> <a class="pull-right">{{ user.email|default:"未在设置中更新" }}</a>
                    </li>
                    <li class="list-group-item">
                        <b>公司</b> <a class="pull-right">{{ user.company|default:"未在设置中更新" }}</a>
                    </li>
                    <li class="list-group-item">
                        <b>所属团队</b> <a class="pull-right">{{ user.department|default:"未在设置中更新" }}</a>
                    </li>
                    <li class="list-group-item">
                        <b>联系电话</b> <a class="pull-right">{{ user.mobile|default:"未在设置中更新" }}</a>
                    </li>
                    <li class="list-group-item">
                        <b>上次登陆时间</b> <a class="pull-right">{{ user.last_login }}</a>
                    </li>
                    <li class="list-group-item">
                        <b>系统权限开始时间</b> <a class="pull-right">{{ user.valid_begin_time }}</a>
                    </li>
                    <li class="list-group-item">
                        <b>系统权限结束时间</b> <a class="pull-right">{{ user.valid_end_time|default:"账户属于永久性账户" }}</a>
                    </li>

                </ul>


            </div>
            <!-- /.box-body -->
        </div>
        <!-- /.box -->


        <!-- /.box -->
    </div>
    <div class="col-md-6">
        <!-- About Me Box -->
        <div class="box box-primary">
            <div class="box-header with-border">
                <h2>关于我</h2>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
                <h3><i class="fa fa-book margin-r-5"></i>自我介绍</h3>

                <p class="text-muted" style="height:225px;font-size: 20px">

                    &nbsp;&nbsp;&nbsp;&nbsp;{{ user.memo|linebreaksbr }}
                </p>

                <hr>
                <a href="{% url 'users:edit_my_information' %}" class="btn btn-primary pull-right"><b>编辑个人信息</b></a>

            </div>

            <!-- /.box-body -->
        </div>


    </div>



{% endblock %}

templates/user/user_info.html
{% extends "base.html" %}
{% load staticfiles %}
{% block head %}
    查看用户信息
{% endblock %}
{% block css %}

    <style>
        .kind-content {
            width: 100%;
            min-height: 200px;
        }
    </style>
{% endblock %}

{% block content %}
    <ol class="breadcrumb" style="margin-bottom: 0;">
        <li><a href="#" style="font-size: large">个人中心</a></li>
        <li class="active" style="font-size: large">查看用户信息</li>
    </ol>
    <div class="col-md-12">

        <!-- Profile Image -->
        <div class="box box-primary">
            <div class="box-body box-profile">
                {% if user.photo %}
                    <img src="{{ user.photo | striptags }}" class="profile-user-img img-responsive img-circle"
                         id="my_photo" name="user_face" alt="User profile picture">
                {% else %}
                    <img name="user_face" src="{% static '/img/evelyn.png' %}"
                         class="profile-user-img img-responsive img-circle"
                         id="my_photo" alt="User profile picture">
                {% endif %}



                <h3 class="profile-username text-center">{{ user.username }}</h3>

                <p class="text-muted text-center">{{ user.postion }}</p>

                <ul class="list-group list-group-unbordered">
                    <li class="list-group-item">
                        <b>邮箱(填写邮箱后也可作为登录账号)</b> <a class="pull-right">{{ user.email|default:"未在设置中更新" }}</a>
                    </li>
                    <li class="list-group-item">
                        <b>公司</b> <a class="pull-right">{{ user.company|default:"未在设置中更新" }}</a>
                    </li>
                    <li class="list-group-item">
                        <b>所属团队</b> <a class="pull-right">{{ user.department|default:"未在设置中更新" }}</a>
                    </li>
                    <li class="list-group-item">
                        <b>联系电话</b> <a class="pull-right">{{ user.mobile|default:"未在设置中更新" }}</a>
                    </li>

                </ul>

                <div class="box-header with-border">
                    <h3>关于我</h3>
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                    <h4><i class="fa fa-book margin-r-5"></i>自我介绍</h4>

                    <p class="text-muted" style="height:150px;font-size: 16px">

                        {% if user.memo %}

                            {{ user.memo|linebreaksbr }}
                        {% else %}
                            还没有填写
                        {% endif %}
                    </p>

                    <hr>

                </div>


            </div>
            <!-- /.box-body -->


            <!-- /.box-body -->
        </div>
    </div>
    <!-- /.box -->



{% endblock %}